EshopCar/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('viewer.urls', namespace='viewer')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'))

]

viewer/urls.py
from django.conf.urls.static import static
from django.urls import path

from EshopCar import settings
from viewer import views
from viewer.views import HomeView, ProductView, OrderSummaryView, CheckoutView, PaymentView, add_to_cart, \
    remove_from_cart, reduce_quantity_item, ProductCreateView, ProductUpdateView, ProductDeleteView, CarbrandListView, \
    search_product, ProductDetailView, SignUpView, MyCarListView

app_name = 'viewer'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('product/<pk>/', ProductView.as_view(), name='product'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('add-to-cart/<pk>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<pk>/', remove_from_cart, name='remove-from-cart'),
    path('reduce-quantity-item/<pk>/', reduce_quantity_item, name='reduce-quantity-item'),
    path('create', ProductCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProductUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ProductDeleteView.as_view(), name='delete'),
    path('brands/<str:brand>', CarbrandListView.as_view(), name='brands_products'),
    path('search/', search_product, name='search'),
    path('<int:pk>/', ProductDetailView.as_view(), name='products_detail'),
    path('accounts/sign-up/', SignUpView.as_view(), name='sign_up'),
    path('contact/', views.contact, name='contact'),
    path('profile/<username>/<int:user_id>/', MyCarListView.as_view(), name='mycar_list'),
    path('profile/<username>/', views.user_profile, name='user_profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

viewer/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db.models import CharField, ForeignKey, DO_NOTHING, ImageField, DateField
from django.shortcuts import reverse
from django_countries.fields import  CountryField
from django.db import models


class Brand(models.Model):
    name = CharField(max_length=55)

    def __str__(self):
        return f'{self.name}'


class Fuel(models.Model):
    name = CharField(max_length=55)

    def __str__(self):
        return f'{self.name}'


class Transmission(models.Model):
    name = CharField(max_length=55)

    def __str__(self):
        return f'{self.name}'


class Item(models.Model):
    item_name = models.CharField(max_length=100)
    price = models.FloatField()
    produced = DateField()
    color = CharField(max_length=55)
    transmission = ForeignKey(Transmission, on_delete=DO_NOTHING)
    fuel = ForeignKey(Fuel, on_delete=DO_NOTHING)
    brand = ForeignKey(Brand, on_delete=DO_NOTHING)
    description = models.TextField()
    image = ImageField(upload_to='images/')
    discount_price = models.FloatField(blank=True, null=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True)

    def __str__(self):
        return self.item_name

    def get_absolute_url(self):
        return reverse("viewer:product", kwargs={
            "pk" : self.pk

        })

    def get_add_to_cart_url(self):
        return reverse("viewer:add-to-cart", kwargs={
            "pk" : self.pk
        })

    def get_remove_from_cart_url(self):
        return reverse("viewer:remove-from-cart", kwargs={
            "pk" : self.pk
        })

class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.item_name}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_discount_item_price()
        return self.get_total_item_price()



class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    checkout_address = models.ForeignKey(
        'CheckoutAddress', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.user.username

    def get_total_price(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total


class CheckoutAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

class Payment(models.Model):
    stripe_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

templates/base.html
{% load static  %}
{% load cart_template_tags %}

<html {% if LANGUAGE_CODE %}lang="{{ LANGUAGE_CODE }}"{% endif %}>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Autobazar</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>


</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: dodgerblue;">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'viewer:home' %}">Car shop</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'viewer:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'viewer:contact' %}">Contact</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'viewer:create' %}">Sell your car </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Brand
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">

                        <li><a class="dropdown-item" href="/brands/Fiat">Fiat</a></li>
                        <li><a class="dropdown-item" href="/brands/Ford">Ford</a></li>
                        <li><a class="dropdown-item" href="/brands/Mercedes">Mercedes</a></li>
                        <li><a class="dropdown-item" href="/brands/Škoda">Škoda</a></li>
                        <li><a class="dropdown-item" href="/brands/Toyota">Toyota</a></li>
                        <li><a class="dropdown-item" href="/brands/BMW">BMW</a></li>

                    </ul>
                </li>
            </ul>
        </div>
        <div class="navbar-nav ml-auto">
            <div class="nav-item dropdown">
                {% if user.is_authenticated %}
                    <div class="nav-link" >
                        <a  href="{% url 'viewer:user_profile' username=user.username %}" style="color: white; font-size: 20px; font-style: normal; margin-left: -50px"> {% if user.first_name %}{{ user.first_name}}
                            {% else %}{{ user.username}} </a>
                    </div>

                    <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">
                        {% endif %}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item text-right" href="{% url 'logout' %}">Logout</a>
                        <a class="dropdown-item text-right" href="{% url 'password_change' %}">Change Password</a>
                    </div>
                {% else %}
                    <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">Please log in</a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item text-right" href="{% url 'login' %}">Login</a>
                        <a class="dropdown-item text-right" href="{% url 'viewer:sign_up' %}">Sign Up</a>
                    </div>
                {% endif %}
            </div>
        </div>
        <div><b span style="color: black;"><a href="{% url 'viewer:order-summary' %}" class="button" style="color: white"> Basket </b><i class="fa fa-shopping-cart ml-1"></i></a>
        </div>
    </div>
</nav>
<div class="container-fluid" style="width: 85%">
    <div class="jumbotron">
        <!-- Jumbotron -->
        <!-- Background image -->
            <div
            class="bg-image d-flex justify-content-center align-items-center"
            style="
            background-image: url('https://images.unsplash.com/photo-1544894079-4184d7a29169?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1436&q=80');
            height:25vh; margin: 48px; margin-top: -26px;
            "
            >
            <h1 class="text-white">Welcome to Car Eshop</h1>
            </div>
        <!-- Background image -->

        <!-- Jumbotron -->
        {% block content %}{% endblock %}

        <a class="weatherwidget-io" href="https://forecast7.com/cs/50d0814d44/prague/" data-label_1="PRAHA" data-days="5" data-theme="retro-sky" >PRAHA</a>
        <script>
            !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src='https://weatherwidget.io/js/widget.min.js';fjs.parentNode.insertBefore(js,fjs);}}(document,'script','weatherwidget-io-js');
        </script>
        <br>
        {% include "footer.html" %}


    </div>
</div>

</body>

</html>

templates/brand_list.html
{% extends "base.html" %}

{% block title %}
    Brandlist
{% endblock %}

{% block content %}

    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                <div class="col-12 pb-5"><h1> All {{carbrandlist.carbrand}} cars</h1></div>
                {% for item in carbrandlist.items %}
                    <div class="col-md-4">
                        <a class="text-dark" href="#">
                            <div class="card mb-4 box-shadow">
                                <img src="{{ item.image.url }}" class="card-img-top" alt="Tu ma byt obrazok">
                                <div class="card-body">
                                    <h2 style="font-size:18px;font-weight:bold">{{item.item_name|truncatechars:50}}</h2>
                                    <p class="card-text">{{item.price|truncatechars:50}} CZK</p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <small class="text-muted">9 mins</small>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}

            </div>
        </div>
    </div>

{% endblock %}

templates/checkout.html
{% extends 'base.html' %}
{% comment %} {% load crispy_forms_tags %} {% endcomment %}

{% block content %}

    <main >
        <div class="container wow fadeIn">

            <!-- Heading -->
            <h2 class="my-5 h2 text-center">Checkout form</h2>

            <!--Grid row-->
            <div class="row">

                <!--Grid column-->
                <div class="col-md-8 mb-4">

                    <!--Card-->
                    <div class="card">

                        <!--Card content-->
                        <form method="POST" class="card-body">
                            {% csrf_token %}
                            <!--address-->
                            <div class="md-form mb-5">
                                {{ form.street_address }}
                                <label for="address" class="">Address</label>
                            </div>

                            <!--address-2-->
                            <div class="md-form mb-5">
                                {{ form.apartment_address }}
                                <label for="address-2" class="">Address 2 (optional)</label>
                            </div>

                            <!--Grid row-->
                            <div class="row">

                                <!--Grid column-->
                                <div class="col-lg-4 col-md-12 mb-4">
                                    <label for="country">Country</label>
                                    {{ form.country }}
                                </div>
                                <!--Grid column-->

                                <!--Grid column-->
                                <div class="col-lg-4 col-md-6 mb-4">

                                    <label for="zip">Zip</label>
                                    {{ form.zip }}
                                    <div class="invalid-feedback">
                                        Zip code required.
                                    </div>

                                </div>
                                <!--Grid column-->

                            </div>
                            <!--Grid row-->

                            <hr>

                            <div class="custom-control custom-checkbox">
                                <input {% if form.same_billing_address.value %}checked{% endif %} type="checkbox" class="custom-control-input" name="same_billing_address" id="same-address">
                                <label class="custom-control-label" for="same-address">Shipping address is the same as my billing address</label>
                            </div>
                            <div class="custom-control custom-checkbox">
                                <input {% if form.save_info.value %}checked{% endif %} type="checkbox" class="custom-control-input" name="save_info" id="save-info">
                                <label class="custom-control-label" for="save-info">Save this information for next time</label>
                            </div>

                            <hr>

                            <div class="d-block my-3">
                                {% for value, name in form.fields.payment_option.choices %}
                                    <div class="custom-control custom-radio">
                                        <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input" required>
                                        <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                                    </div>
                                {% endfor %}
                            </div>

                            <hr class="mb-4">
                            <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

                        </form>

                    </div>
                    <!--/.Card-->

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-4 mb-4">

                    <!-- Heading -->
                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-muted">Your cart</span>
                        <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
                    </h4>

                    <!-- Cart -->
                    <ul class="list-group mb-3 z-depth-1">

                        {% for order_item in order.items.all %}
                            <li class="list-group-item d-flex justify-content-between lh-condensed">
                                <div>
                                    <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.item_name }}</h6>
                                    <small class="text-muted">{{ order_item.item.description }}</small>
                                </div>
                                <span class="text-muted">{{ order_item.get_final_price }}</span>
                            </li>
                        {% endfor %}


                        {% comment %} <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>EXAMPLECODE</small>
              </div>
              <span class="text-success">-$0</span>
            </li> {% endcomment %}
                        <li class="list-group-item d-flex justify-content-between">
                            <span>Total (USD)</span>
                            <strong>{{ order.get_total_price }}</strong>
                        </li>
                    </ul>
                    <!-- Cart -->

                </div>

            </div>
            <!--Grid row-->

        </div>
    </main>
    <!--Main layout-->

{% endblock content %}

templates/contact.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <!--Section: Contact v.1-->
    <section class="section pb-5">

        <!--Section heading-->
        <h2 class="section-heading h1 pt-4">Contact us</h2>
        <!--Section description-->
        <p class="section-description pb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit, error
            amet numquam iure provident voluptate esse quasi, veritatis totam voluptas nostrum quisquam eum porro a
            pariatur accusamus veniam.</p>

        <div class="row">

            <!--Grid column-->
            <div class="col-lg-5 mb-4">

                <!--Form with header-->
                <div class="card">

                    <div class="card-body">
                        <!--Header-->
                        <div class="form-header blue accent-1">
                            <h3><i class="fa fa-envelope"></i> Write to us:</h3>
                        </div>

                        <p>We'll write rarely, but with only the best content.</p>
                        <br>

                        <!--Body-->
                        <div class="md-form">
                            <label for="form-name">Your name</label>
                            <input type="text" id="form-name" class="form-control">

                        </div>

                        <div class="md-form">
                            <label for="form-email">Your email</label>
                            <input type="text" id="form-email" class="form-control">

                        </div>

                        <div class="md-form">
                            <label for="form-Subject">Subject</label>
                            <input type="text" id="form-Subject" class="form-control">

                        </div>

                        <div class="md-form">
                            <label for="form-text">Text</label>
                            <textarea id="form-text" class="form-control md-textarea" rows="3"></textarea>

                        </div>

                        <div class="text-center mt-4">
                            <button class="btn btn-primary">Submit</button>
                        </div>

                    </div>

                </div>
                <!--Form with header-->

            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-lg-7">

                <!--Google map-->
                <div id="map-container-google-11" class="z-depth-1-half map-container-6" style="height: 400px">
                    <iframe scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;q=w%2056th%20St+(My%20Business%20Name)&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed" width="100%" height="600" frameborder="0"></iframe>
                </div>

                <br>
                <!--Buttons-->
                <div class="row text-center">
                    <div class="col-md-4">

                        <p>New York, NY 94126</p>
                        <p>United States</p>
                    </div>

                    <div class="col-md-4">

                        <p>+ 01 234 567 89</p>
                        <p>Mon - Fri, 8:00-22:00</p>
                    </div>

                    <div class="col-md-4">

                        <p>info@gmail.com</p>
                        <p>sale@gmail.com</p>
                    </div>
                </div>

            </div>
            <!--Grid column-->

        </div>

    </section>
    <!--Section: Contact v.1-->

{% endblock %}

templates/form.html
{% extends "base.html" %}

{% block content %}

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="">{{ form.as_p }}</table>
        <input type="submit" value="Submit" class="btn btn-primary">

    </form>

{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block content %}


    <form action="/search/" method="GET" style="text-align: center;">
        {% csrf_token %}
        <input type="text" name="name">
        <input type="submit" name="submit" value="Search">
    </form>



    {% for result in results %}

        <p>{{item_name}}</p>

    {% endfor %}






            <div class="container-fluid ">
                {% for item in item_list%}
            <div class="row row-cols-1 row-cols-md-3" style="display: inline-flex">


            <div class="col mb-4">
                <div class="card">
                    <a href="{% url 'viewer:product' pk=item.id %}"><img src="{{ item.image.url }}" class="card-img-top" alt="Tu ma byt obrazok" style="height: 250px;width: 350px"></a>
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <a href="{% url 'viewer:product' pk=item.id %}">{{ item.item_name }}</a>
                        <p class="card-text">Price: {{ item.price }} CZK</p>
                    </div>
                </div>
            </div>



        </div>
                {% endfor %}
        </div>



{% endblock %}

templates/order_summary.html
{% extends 'base.html' %}

{% block content %}

    <main>
        <div class= "container">
            <div class="table-responsive text-nowrap">
                <h3>
                    <strong>Your Cart</strong>
                </h3>
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Item Name</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Total Item Price</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for order_item in object.items.all %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ order_item.item.item_name }}</td>
                            <td>
                                {% if order_item.item.discount_price %}
                                    <del>{{ order_item.item.price}} CZK</del>
                                    {{ order_item.item.discount_price }} CZK
                                {% else %}
                                    {{ order_item.item.price}} CZK
                                {% endif %}

                            </td>
                            <td>
                                <a href="{% url 'viewer:reduce-quantity-item' order_item.item.pk %}"><i class="fa fa-minus mr-2"></i></a>
                                {{ order_item.quantity }}
                                <a href="{% url 'viewer:add-to-cart' order_item.item.pk %}"><i class="fa fa-plus ml-2"></i></a>
                            </td>
                            <td>
                                {% if order_item.item.discount_price %}
                                    {{ order_item.get_discount_item_price }} CZK
                                    <span class="badge badge-success" >Saved CZK{{ order_item.get_amount_saved }}</span>
                                {% else %}
                                    {{ order_item.get_total_item_price}} CZK
                                {% endif %}
                                <a href="{% url 'viewer:remove-from-cart' order_item.item.pk %}">
                                    <i class="fa fa-trash float-right text-danger"></i>
                                </a>

                            </td>
                        </tr>

                    {% empty %}
                        <tr>
                            <td colspan="5">Your Cart Empity</td>
                        </tr>

                        <tr>
                            <td colspan="5">
                                <a href="/" class="btn btn-primary float-right">Continue Shopping</a>
                            </td>
                        </tr>

                    {% endfor %}

                    {% if object.get_total_price %}
                        <tr>
                            <td colspan="4"><b>Total Order Price</b></td>
                            <td>{{ object.get_total_price }} CZK</td>
                        </tr>
                        <tr>
                            <td colspan="5">
                                <a href="{% url 'viewer:checkout' %}" class="btn btn-warning float-right ml-2">Checkout</a>
                                <a href="/" class="btn btn-primary float-right">Continue Shopping</a>
                            </td>
                        </tr>

                    {% endif %}

                    </tbody>
                </table>

            </div>
        </div>
    </main>

{% endblock content %}

templates/product.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <h1>Product detail</h1>


    <div class="card mb-3" style="max-width: 1700px;padding: 20px">
        <div class="row no-gutters">
            <div class="col-md-4">
                <img src="{{ item.image.url }}" class="card-img" alt="..." style="margin: 10px; margin-top: 30px">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">{{ item.item_name }}</h5>
                    <p class="card-text">Transmission: {{ item.transmission }}</p>
                    <p class="card-text">Fuel: {{ item.fuel }}</p>
                    <p class="card-text">Color: {{ item.color }}</p>
                    <p>
                        <a class="card-text" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                            Description
                        </a>

                    </p>
                    <div class="collapse" id="collapseExample">
                        <div class="card card-body">
                            {{ item.description}}
                        </div>
                    </div>
                    <p class="card-text">Price: {{ item.price }} CZK</p>
                    <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                </div>
                <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p" style="margin-left: 20px" >Add to cart
                    <i class="fa fa-shopping-cart ml-1"></i>
                </a>
                <br>
                <br>
                {{ object.get_quantity_in_chart }}
                <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p" style="margin-left: 20px" >Remove From cart
                    <i class="fa fa-trash ml-1"></i>
                </a>
                {% if user.is_authenticated %}
                {% if user == item.user %}

                <a href="{% url 'viewer:delete' pk=item.pk %}" class="btn btn-danger btn-md my-0 p" style="margin-left: 20px" >Delete
                    <i class="fa fa-delete ml-1"></i>
                </a>

                {% endif %}
                {% endif %}

            </div>
        </div>
    </div>



{% endblock %}

templates/product_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <h1>Product detail</h1>


    <div class="card" style="width: 18rem;">
        <img src="{{ item.image.url }}" class="card-img-top" alt="Tu ma byt obrazok">
        <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">Title:{{ item.item_name }}</p>
            <a href="{% url 'viewer:delete' %}" class="btn btn-primary">Buy</a>
        </div>
    </div>

{% endblock %}